### ISSUE TITLE
Can't assign different tap-keys

### ISSUE THREAD

**Issue by ezequielmg** [open2jamorg/open2jam#15]
I compiled the game from source and i've realized that keys configuration can't be changed.

It asks to change the key, but after that nothing could be done, key was not changed, neither the window closes.
I had to hardcode my predefined assigned keys on source then I compiled it to accomplish it.

I'm using Mac OSX 10.7 with latest java version. I dunno what could be the problem so far :)

**Comment by mrcdk** [comment]
Hi there, I think i kno... wait... Ezequiel moreno garcia? 
![](http://www.tcmb.eu/uploads/yao-ming-meme2.jpg)
Le den al inglés entonces XD Creo que el problema está en que en mac OSX el hilo que usa swing coge todo el foco del teclado, ya lo tuvimos antes y lo arreglamos solo en el juego en si, pero no en los demás sitios que usan ogl (como es el caso de la configuración del teclado) Ahora mismo no tengo tiempo para arreglarlo, lo intentaré arreglar lo antes posible xD

In case I just fail and you aren't spanish, I think I know the problem is. It's because on mac osx the swing thread gets all the keyboard focus. We had that same problem in the player and fixed it, but not in other places using ogl. (like the key config) Right now I don't have time to fix it but I will try soon enough.

**Comment by ezequielmg** [comment]
Oh esta bien!! Me estoy metiendo de lleno a Java, igual despues en lo que pueda apoyarte aqui andare!!
Y si, ese es mi nombre,, :P.. i wonder who you are... : D creo que nos conocemos entonces :P!!

Mis respetos man, le pegas a Java como bien!! xD :)
Estoy disfrutando de open2jam mas que con las versiones soloistas =P

Edit: chaosfox, you're such a big java coder!! thumbs up! :)

**Comment by mrcdk** [comment]
xD El nombre me salía en el e-mail que llega de github cada vez que hay movimiento xD No creo que nos conozcamos xD
La mayor parte del código es de chaosfox, el que empezó todo esto, yo estoy igual que tu, empezando con Java xD El si que es el amo. 

Me alegro que te guste aunque tiene unos bugs tremendos (como tengas un solo miss se vuelve loco el programa y no acierta una xD), estoy pensando en portar el player a la librería [libgdx](http://code.google.com/p/libgdx/) para poder sacarlo en android (y porque es mucho mejor que lo que tenemos ahora xD) Aunque estoy esperando a que saquen una nueva versión porque están cambiando/añadiendo cosas que me harían la tarea mas fácil :D 

A parte en [esta rama](https://github.com/chaosfox/open2jam/tree/separated_parsers) estoy escribiendo parsers como un loco xD (bueno, quizás no... pero lo intento xD)

Por último, intenta escribir español e inglés o solo inglés porque chaosfox no entiende el español xD pobre xD

---

xD Your name was in the e-mail that sends github any time there is movement here xD I don't think we know each other xD
Almost all the code is written by chaosfox, he started all this, I'm like you, starting with java xD He is the boss here xD

I'm glad you like this project even it has a lot of bugs (like if you miss a note it will go crazy and judge all the others wrong xD) I want to port the player to [libgdx](http://code.google.com/p/libgdx/) to be able to launch it on android (and because it's better than we have right now xD) But I'm waiting them to launch a new version, they are adding/changing things that would make the port easier :D

In [this branch](https://github.com/chaosfox/open2jam/tree/separated_parsers) I'm writing more parsers.

Last, try to write in spanish and english or english only, chaosfox can't understand spanish xD poor guy XD
