### ISSUE TITLE
Gui changes

### ISSUE THREAD

**Issue by mrcdk** [open2jamorg/open2jam#6]
In the branch gui_changes I will be uploading gui related changes.

**Comment by chaosfox** [comment]
not sure if you already noticed but you can't make the window smaller because the components disappear instead of getting smaller with the window, I think you can set the minimumSize of the components to allow the swing fit then in the window instead of hiding, also set a minimumSize for the window itself, so when the window is in the smallest size possible it doesn't allow to make it smaller.

**Comment by mrcdk** [comment]
Done, I wanted to do this but wasn't sure because swing editor is... you know... not the perfect thing to mess up xD

**Comment by mrcdk** [comment]
I've deleted the custom size settings, mainly because it can make lwjgl break everything if you set some random numbers.

**Comment by chaosfox** [comment]
what you mean deleted ? I need that. some computers show messed up
resolutions on the combo box and the custom size helps.
What you mean by random numbers ? breaking on non-sense
numbers(negative, bigger than screen,etc) is ok

On Fri, Jun 10, 2011 at 6:04 PM, mrcdk
reply@reply.github.com
wrote:

**Comment by mrcdk** [comment]
Okok, i will bring it back, but it won't be saved xD

**Comment by mrcdk** [comment]
I've added a mock up of how the skin configuration should look... well, maybe with some more changes xD. The idea i have in mind is, have a default skin (the one we have right now) in the jar file, so it can't be deleted. And have a dir called ......... mmm... "skins" where the user have to put the skin file (maybe zipped?). The program will load all the skins of that dir and also the default one.

**Comment by chaosfox** [comment]
these have been merged already if I remember correctly so I will close this.
